# Link repository with Travis CI
# https://travis-ci.org/

# Master branch only
branches:
  except:
    - gh-pages

# Start the databases
# See https://docs.travis-ci.com/user/database-setup/
# addons:
#   postgresql: "9.4"

# services: 
#   - postgresql

# Set the language
language: python
python:
    - "2.7.13"
    - "3.5"

# before_script:
#  - psql -c 'create database mimic_test;' -U postgres

# command to install dependencies
install:
  - pip install .

# command to run tests
script: nosetests