# Link repository with GitHub Actions
# https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions

# Master branch only
name: run-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Set the language, install dependencies, and run the tests
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          python -m poetry install
      - name: Run nosetests
        run: |
          nosetests

  test-deb10-i386:
    runs-on: ubuntu-latest
    container: i386/debian:10
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
                  python3-matplotlib \
                  python3-numpy \
                  python3-pandas \
                  python3-requests \
                  python3-scipy \
                  python3-nose \
                  git

      # Note: "actions/checkout@v2" requires libstdc++6:amd64 to be
      # installed in the container.  To keep things simple, use
      # "actions/checkout@v1" instead.
      # https://github.com/actions/checkout/issues/334
      - uses: actions/checkout@v1

      - name: Run nosetests
        run: |
          nosetests3
